# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aarch64 = {
    pname = "aarch64";
    version = "1.16.4b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.16.4b/zen-aarch64.AppImage";
      sha256 = "sha256-pjb8BAra3GXt9sw+FjIPaP2yzKM3f9jFbaIvdIOJ63Y=";
    };
  };
  darwin = {
    pname = "darwin";
    version = "1.16.4b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.16.4b/zen.macos-universal.dmg";
      sha256 = "sha256-jGOyE26JntBMQBu7w+pwHpKMFCd+lx6SyjapX0KCQUc=";
    };
  };
  x64 = {
    pname = "x64";
    version = "1.16.4b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.16.4b/zen-x86_64.AppImage";
      sha256 = "sha256-+VRhJHb7RNAniuOWZAeUB5sTUjS0vu8DI0SOKJZbh/Q=";
    };
  };
}
